---
name: Pyright

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jakebailey/pyright-action@v2
        with:
          version: 1.1.311
